# Generated by Django 5.1.1 on 2024-12-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
    ]
