# Generated by Django 5.1.1 on 2025-01-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpresetcalorie',
            name='food_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/category/'),
        ),
    ]
